name: General Issue
description: Please fill out the form below to submit an issue.
labels: []
assignees: []

body:
  - type: textarea
    id: issue_description
    attributes:
      label: "Issue Description"
      description: "Please provide a detailed description of your issue."
      placeholder: "Describe your issue here..."
      value: ""

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: |
        **Please read the [PSF Code of Conduct][CoC] first.**
        [CoC]: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md
      options:
        - label: "I am aware that participants in this repository must follow the PSF Code of Conduct."
          required: true

